version: '3.9'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    networks:
      internal_network:
        aliases:
          - proxy.local
    ports:
      - '80:80'
      - '81:81'
      - '8000:81'
      - '443:443'
      - '1883:1883'
      - '55555:55555'
    volumes:
      - nginx-data:/data
      - letsencrypt:/etc/letsencrypt
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    env_file:
      - stack.env
    networks:
      internal_network:
        aliases:
          - gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.maxtar.de'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Host" => "gitlab.maxtar.de",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['gitlab_https'] = true
        gitlab_rails['internal_api_url'] = 'http://gitlab.local'
    ports:
      - '2424:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    networks:
      internal_network:
        aliases:
          - gitlab-runner.local
    volumes:
      - local-ca:/etc/gitlab-runner/certs
      - gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - '5000:5000'
    networks:
      internal_network:
        aliases:
          - registry.local
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Private Docker Registry"
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth

volumes:
  local-ca:
  nginx-data:
  letsencrypt:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner:
  registry_data:
  registry_auth:

networks:
  internal_network:
