version: '3.9'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    networks:
      internal_network:
        aliases:
          - proxy.local
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  nginx-data:
  letsencrypt:

networks:
  internal_network:
